// this dhould be autogenerated
#pragma once

// include headers
#include "WSystems/WSystemMacros.hpp"
#include "WSystems/WSystems.hpp"
#include "WSystems/WSystemRegister.hpp"

// Start Register Generation
START_DEFINE_WSYSTEMS_REG(WENGINE, WSYSTEMS)

CALL_WSYSTEM_REGISTER(UpdateRenderTransformSystem)

END_DEFINE_WSYSTEMS_REG()
