// This should be autogenerated
#pragma once

// include headers
#include "WSystems/WSystemMacros.hpp"
#include "WSystems/WSystems.hpp"
#include "WSystems/WSystemsRegister.hpp"

// Start WSystems Register Generation
START_DEFINE_WSYSTEMS_REG(WENGINE, WSYSTEMS)

    CALL_WSYSTEM_REGISTER(SystemInit_RenderLevelResources)

    CALL_WSYSTEM_REGISTER(SystemInit_InitializeTransformsMatrix)

    CALL_WSYSTEM_REGISTER(SystemInit_CameraInput)

    CALL_WSYSTEM_REGISTER(SystemPre_UpdateMovement)

    CALL_WSYSTEM_REGISTER(SystemPre_CameraInputMovement)

    CALL_WSYSTEM_REGISTER(SystemPost_UpdateRenderCamera)

    CALL_WSYSTEM_REGISTER(SystemEnd_RenderLevelResources)

END_DEFINE_WSYSTEMS_REG()
