// This should be autogenerated
#pragma once

// include headers
#include "WSystems/WSystemMacros.hpp"
#include "WSystems/WSystems.hpp"
#include "WSystems/WSystemsRegister.hpp"

// Start WSystems Register Generation
START_DEFINE_WSYSTEMS_REG(WENGINE, WSYSTEMS)

    CALL_WSYSTEM_REGISTER(System_PostUpdateRenderTransform)

    CALL_WSYSTEM_REGISTER(System_PostUpdateRenderCamera)

    CALL_WSYSTEM_REGISTER(System_InitRenderLevelResources)

    CALL_WSYSTEM_REGISTER(System_EndRenderLevelResources)

END_DEFINE_WSYSTEMS_REG()
