// This should be autogenerated
#pragma once

// include headers
#include "WSystems/WSystemMacros.hpp"
#include "WSystems/WSystems.hpp"
#include "WSystems/WSystemsRegister.hpp"

// Start WSystems Register Generation
START_DEFINE_WSYSTEMS_REG(WENGINE, WSYSTEMS)

    DECLARE_WSYSTEM(WENGINE_API, System_PostUpdateRenderTransform)

    DECLARE_WSYSTEM(WENGINE_API, System_PostUpdateRenderCamera)

    DECLARE_WSYSTEM(WENGINE_API, System_InitRenderLevelResources)

    DECLARE_WSYSTEM(WENGINE_API, System_EndRenderLevelResources)

END_DEFINE_WSYSTEMS_REG()
