// Autogenerated Code: DO NOT EDIT

#ifdef _WCLASS_
#undef _WCLASS_
#endif

#define _WCLASS_ WObject

#include "WReflections/_DEFINE_WCLASS_.hpp"

#undef _WCLASS_

#define _WCLASS_ WActor

#include "WReflections/_DEFINE_WCLASS_.hpp"

#undef _WCLASS_

#define _WCLASS_ WAsset

#include "WReflections/_DEFINE_WCLASS_.hpp"

#undef _WCLASS_

#define _WCLASS_ WComponent

#include "WReflections/_DEFINE_WCLASS_.hpp"

#undef _WCLASS_

#define _WCLASS_ WStaticMeshAsset

#include "WReflections/_DEFINE_WCLASS_.hpp"

#undef _WCLASS_

#define _WCLASS_ WTextureAsset

#include "WReflections/_DEFINE_WCLASS_.hpp"

#undef _WCLASS_


