// Autogenerated Code: DO NOT EDIT
// Order is important, each class should appear below its parent class.

#include "WEngineObjects/WObject.hpp"
#include "WReflections/_DEFFINE_WCLASS_.hpp"

#include "WEngineObjects/WAsset.hpp"
#include "WReflections/_DEFFINE_WCLASS_.hpp"

#include "WEngineObjects/WComponent.hpp"
#include "WReflections/_DEFFINE_WCLASS_.hpp"

#include "WEngineObjects/WEntity.hpp"
#include "WReflections/_DEFFINE_WCLASS_.hpp"

#include "WAssets/WActionAsset.hpp"
#include "WReflections/_DEFFINE_WCLASS_.hpp"

#include "WAssets/WInputMappingAsset.hpp"
#include "WReflections/_DEFFINE_WCLASS_.hpp"

#include "WAssets/WRenderPipelineAsset.hpp"
#include "WReflections/_DEFFINE_WCLASS_.hpp"

#include "WAssets/WRenderPipelineParametersAsset.hpp"
#include "WReflections/_DEFFINE_WCLASS_.hpp"

#include "WAssets/WStaticMeshAsset.hpp"
#include "WReflections/_DEFFINE_WCLASS_.hpp"

#include "WAssets/WTextureAsset.hpp"
#include "WReflections/_DEFFINE_WCLASS_.hpp"

#include "WComponents/WCameraComponent.hpp"
#include "WReflections/_DEFFINE_WCLASS_.hpp"

#include "WComponents/WCameraInputComponent.hpp"
#include "WReflections/_DEFFINE_WCLASS_.hpp"

#include "WComponents/WMovementComponent.hpp"
#include "WReflections/_DEFFINE_WCLASS_.hpp"

#include "WComponents/WStaticMeshComponent.hpp"
#include "WReflections/_DEFFINE_WCLASS_.hpp"

#include "WComponents/WTransformComponent.hpp"
#include "WReflections/_DEFFINE_WCLASS_.hpp"

