#!/bin/bash

if [ -z "$EMSCRIPTENENV" ]; 
then
    EMSCRIPTENENV=false
fi

BUILD_PATH="./build"
mkdir -p $BUILD_PATH

export BUILDTYPE="Debug"

OPTIONS=("Debug" "Release" "Quit")
select opt in "${OPTIONS[@]}"
do
    case $opt in
        "Debug")
            BUILDTYPE="Debug"
            break
            ;;
        "Release")
            BUILDTYPE="Release"
            break
            ;;
        "Quit")
            exit 0
            ;;
        *) 
            echo "Invalid option $REPLY"        
        ;;
    esac
done

echo "Building $BUILDTYPE"

SYSTEM=Linux
ARCH=x86_64

BUILD_PATH="$BUILD_PATH/${SYSTEM}_${ARCH}_${BUILDTYPE}"

if [ "$EMSCRIPTENENV" = true ] ; then
    BUILD_PATH="${BUILD_PATH}_Emscripten"
    # emcmake cmake  -S . -B $BUILD_PATH 
else
    BUILD_PATH="${BUILD_PATH}_Standalone"
    # cmake --build $BUILD_PATH
fi

mkdir -p $BUILD_PATH

export CC=clang
export CXX=clang++
# export CC=gcc
# export CXX=g++

echo "Building $BUILDTYPE for $SYSTEM $ARCH"

if [ "$EMSCRIPTENENV" = true ];
then
    echo "Building for Emscripten"
    emcmake cmake  -S . -B $BUILD_PATH -DCMAKE_BUILD_TYPE=$BUILDTYPE -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
else
    echo "Building for Standalone"
    cmake  -S . -B $BUILD_PATH -DCMAKE_BUILD_TYPE=$BUILDTYPE -DCMAKE_EXPORT_COMPILE_COMMANDS=ON  -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON # -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
fi

cmake --build $BUILD_PATH

exit 0
