#+title: WEng

* Project Structure

* Module Structure
** Directory Tree
*** Modules (PascalCase)

    - ModulesNames _(PascalCase)_
        - CMakeLists.txt (each mmodule will be managed by its own CMakeLists)
        - Source
            - ModuleFile.cpp _(PascalCase)_
        - Include
            - ModuleHeader.h _(PascalCase)_
    - ...

*** Source (PascalCase)

    - WSourceModules _(PascalCase)_
        - CMakeLists.txt (each mmodule will be managed by its own CMakeLists)
        - Source
            - ModuleFile.cpp _(PascalCase)_
        - Include
            - ModuleHeader.h _(PascalCase)_
    - ...

** Namespaces

- All elements, classes, structs and free operations should be placed in a namespace.
      - Namespaces as module abstractions.
      - w<name>::<subname>
            - w<name> : abbreviation of the external module.
            - <subname> : abstraction that groups the operations.

* Modules
** Objectives

Modules should be linkable between them and dinamically linkable with the core application.
Our source modules should avoid unneeded dependencies.
Model controller paradigm.
Data structure design paradigm (memory addresess sorted by component class).
Use standard library for data types. 
Use libraries to solve complex problems.

** WCore
*** Submódulos
**** WCoreTypes
***** Target
Tipos básicos del engine.
Se claran en WCore para evitar las dependencias cruzadas entre módulos.

***** Archivos
- WTexture.hpp
- WGeometry.hpp
- WEngine.hpp
- WMath.hpp
- WRender.hpp

***** Namespaces
- wtp::texture : weng textures subprograms.


** WCommand

/Command Module/

This module will contain the system for command registation, base classes and command queues. 
each module will be responsible of its commands creation and registation in the system.

** WRender

Vulkan Rendering related code

*** Namespaces

- wvk::<label> : weng vulkan subprograms.

** WEngine

/Main Module/

WEngine is the starting point of the aplication, the main function will be here.

WEngine will also load each module dinamically, this way the application can be extended using a plugin system, 
modules for ours.

The engine class will reference to other modules in the aplication.



* Coding Style

** Classes Initial letter

- T -> templates
- B -> Base Clases not Interfaces
- I -> Interfaces
- W -> WEng Object | Engine modules | Engine classes
- E -> Enums

