#+title: WEng

#+startup: content

* Project Structure
** Paradigms

- Data structure design paradigm (memory addresess sorted by component class).

** Module Structure

*** Modules objective

Modules should be linkable between them and dinamically linkable with the core application.

#+BEGIN_SRC plantuml :file images/modules_dependencies_1.png
@startuml

Rectangle WEngine
Rectangle WEngineInterfaces
Rectangle WEngineObjects
Rectangle WCore
Rectangle WLevel
Rectangle WRender

WEngineInterfaces -[dashed]-> WEngineObjects
WEngineInterfaces -[dashed]-> WCore

WEngineObjects -[dashed]-> WCore

WEngine -[dashed]-> WEngineObjects
WEngine -[dashed]-> WEngineInterfaces
WEngine -[dashed]-> WCore

WLevel -[dashed]-> WEngineInterfaces
WLevel -[dashed]-> WEngineObjects
WLevel -[dashed]-> WCore

WRender -[dashed]-> WEngineInterfaces
WRender -[dashed]-> WEngineObjects
WRender -[dashed]-> WCore

@enduml
#+END_SRC

*** Directory Tree
- Source/ModuleName _(PascalCase)_
      - ModuleName.org
      - CMakeLists.txt (each mmodule will be managed by its own CMakeLists)
      - Source
            - ModuleFile.cpp _(PascalCase)_
      - Include
            - ModuleHeader.h _(PascalCase)_
      - PublicGenerated
      - PrivateGenerated
            - DllDef.hpp
      - CompileGenerated
- ...

*** Namespaces

- All code elements (classes, structs, free operations, etc) should be placed in a namespace.
- Namespaces as module abstractions.
- w<name>::<subname>
      - w<name> : <name> is a two letter abbreviation of the external module.
      - <subname> : abstraction name that groups the elements.

* Module List
** WCore
*** WCoreTypes
**** Objective

Tipos básicos del engine.
Se declaran en WCore para evitar las dependencias cruzadas entre módulos.

**** Files

- WCoreTypes/WTexture.hpp
- WCoreTypes/WGeometry.hpp
- WCoreTypes/WEngine.hpp
- WCoreTypes/WMath.hpp
- WCoreTypes/WRenderTypes.hpp

**** Namespaces

- wct::texture
- wct::render
      - Pipeline types (materials)
      - Pipeline parameters types (materials)
      - Lighting types (lights)

** WImporter
*** Objective

Módulo con las implementaciones necesarias para traducir assets externos en objetos nativos del engine.

**** Files

- WImporter/WImporterRegister.hpp
- WImporter/WImporter.hpp

**** Namespaces

- wim::imp_register
      - Abstracciones para registrar importadores al engine.
      - Un importador registrado puede ser invocado usando tan solo la ruta al archivo.

- wim::importer
      - Objetos Importadores para cada tipo de asset, textura, geometríam etc.

** WCommand

/Command Module/

This module will contain the system for command registation, base classes and command queues. 
each module will be responsible of its commands creation and registation in the system.

** WRender
*** WRender
**** Objective

General Rendering related code.

**** Files

- WRender/*

**** Namespaces

- wrd::render
- wrd::shader

*** WVulkan
**** Objective

**** Files

**** Namespaces

- wvk::<label>

**** WVkRender
***** Objective
IRender implementation using Vulkan.

** WEngine
*** Objective

/Main Module/

WEngine is the starting point of the aplication, the main function will be here.

WEngine will also load each module dinamically, this way the application can be extended using a plugin system, 
modules for ours.

The engine class will reference to other modules in the aplication.

*** WEngRender
**** Objective

- Setup render subprograms.
- Subprograms are used in the ECS system.
  
**** Files
- WEngRender/WEngRender.hpp
**** Namespaces
- wng::render

** WEngineObjects
*** Objective

Módulo que contiene los objetos que forman la estructura de datos del engine.

*** WEngineObjects
**** Objective

This module contains all WObject base classes.
From WObject derivates other classes like WComponent, WEntity or WAsset.
Each WObject has a WClass associated. This WClass instance contains relevant data about the WObject class.

WObject is an object that can be tracked by the engine. WObjects has a kind of reflection implemented.

The WObject and WClass system has its own section.

*** WComponents

**** Objective

Componentes almacenan los datos que definen una escena. Se puede pensar en ellos como en una base de datos.
Los componentes están asociados a actores. formando así entidades compuestas de componentes.

**** Files

- WComponents/light/WAmbientLightComponent.hpp
- WComponents/light/WDirectionalLightComponent.hpp
- WComponents/light/WPointLightComponent.hpp

**** Namespace

- wcm::light
- wcm::transform
- wcm::geometry

*** WAssets

** WObject and WClass Template/Reflection
*** WPROPERTY macro
:PROPERTIES:
:CUSTOM_ID: WPROPERTY
:END:
**** Objective

- Property self knowledge (type, names, ranges, etc).
- Get_ Set_ method access.
- Serialization.

*** WClass.WEngine.hpp

**** Objective

WClass generation for current WObject.

**** Namespace

- wrf::wclass

*** WOBJECT_BODY macro

* Shaders

- language *Slang*
- [[https://docs.shader-slang.org/en/latest/external/core-module-reference/global-decls/math.html][slang functions reference]]

* WRender
** Static Dynamic Lights UBO updates
:PROPERTIES:
:CUSTOM_ID: StaticDynamicLightsUBOUpdates
:END:

id arrays like :
[SLight 1 , ..., SLight n, Dlight 1,...,Dlight m]

Using a light structure like this allows to perform per frame light updates in a efficiente way.
lightingUBO contains an array for each light type. this array is ensured that will behave lika a dense/sparse set.

So if any update is placed only at the Dynamic lights area, Static lights will never lose its Dense set positions.
All dynamic updates can be done in memory ranges, avoiding that any update range overlaps with the static lights memory area.

- Notes
      - Static lights requires only one UBO (no frames in flight).
      - Dynamic lights could be updated each frame.


* Coding Style

** Classes Initial letter

- T -> templates
- I -> Interfaces
- W -> WEng Object | Engine modules | Engine classes
- E -> Enums

